import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quiz App - Learn Better",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 1. Эхлээд env-ээс уншиж үзнэ, хэрэв байхгүй бол шууд утгыг нь онооно
  const clerkKey =
    process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY ||
    "pk_test_bmljZS1kb2ctNzAuY2xlcmsuYWNjb3VudHMuZGV2JA";

  console.log("Building with Key:", clerkKey ? "Key exists" : "Key is missing");

  return (
    <ClerkProvider publishableKey={clerkKey}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-between items-center p-4 gap-4 h-16 border">
            <p className="ml-6 text-2xl font-semibold  text-black bg-clip-text bg-[length:200%_200%]">
              Quiz App
            </p>
            <div className="flex items-center gap-4 mr-6">
              <SignedOut>
                <SignInButton mode="modal">
                  <span className="cursor-pointer font-medium text-sm text-black hover:text-[#6c47ff] hover:underline">
                    Sign In
                  </span>
                </SignInButton>
                <SignUpButton mode="modal">
                  <button className="bg-black hover:bg-[#5b3ce6] text-white rounded-full font-medium h-8 px-4 transition-colors">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton afterSignOutUrl="/" />
              </SignedIn>
            </div>
          </header>
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
